services:

  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgres://challenge:challenge@db:5432/challenge"
#  celery:
#    environment:
#        - DJANGO_SETTINGS_MODULE=challenge.settings.dev
#    build: .
#    command: celery -A challenge worker -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#      - redis
#  celery-beat:
#    environment:
#      - DJANGO_SETTINGS_MODULE=challenge.settings.dev
#    build: .
#    command: celery -A challenge beat -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#      - redis


volumes:
  postgres_data:
  redis_data:
